apiVersion: v1
kind: Pod
metadata:
  name: mongo-single
spec:
  containers:
    - name: mongo-container
      image: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
      ports:
        - name: mongo-port
          containerPort: 27017
          protocol: TCP


# usage: kubectl port-forward mongo-single 27017:27017
