apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: webdevops/php-nginx
          ports:
            - name: nginx-port
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: nginx-index
            mountPath: /app/
      volumes:
        - name: nginx-index
          configMap:
            name: nginx-index
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.php: |
    <?php
    echo '=== '.gethostname().' ===';
    ?>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
  selector:
    app: nginx

# kubectl exec nginx-cg2fv -it -- bash
# curl http://nginx
