apiVersion: v1
kind: Pod
metadata:
  name: nginx-single
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP


# usage: kubectl port-forward nginx-single 8080:80
